export const EPISODES_IMAGES: Record<string, any> = {
  // Season 1
  "s1/ep1": require("@/assets/images/episodes/s1/ep1.webp"),
  "s1/ep2": require("@/assets/images/episodes/s1/ep2.webp"),
  "s1/ep3": require("@/assets/images/episodes/s1/ep3.webp"),
  "s1/ep4": require("@/assets/images/episodes/s1/ep4.webp"),
  "s1/ep5": require("@/assets/images/episodes/s1/ep5.webp"),
  "s1/ep6": require("@/assets/images/episodes/s1/ep6.webp"),
  "s1/ep7": require("@/assets/images/episodes/s1/ep7.webp"),
  "s1/ep8": require("@/assets/images/episodes/s1/ep8.webp"),
  "s1/ep9": require("@/assets/images/episodes/s1/ep9.webp"),
  "s1/ep10": require("@/assets/images/episodes/s1/ep10.webp"),
  "s1/ep11": require("@/assets/images/episodes/s1/ep11.webp"),
  "s1/ep12": require("@/assets/images/episodes/s1/ep12.webp"),
  "s1/ep13": require("@/assets/images/episodes/s1/ep13.webp"),

  // Season 2
  "s2/ep1": require("@/assets/images/episodes/s2/ep1.webp"),
  "s2/ep2": require("@/assets/images/episodes/s2/ep2.webp"),
  "s2/ep3": require("@/assets/images/episodes/s2/ep3.webp"),
  "s2/ep4": require("@/assets/images/episodes/s2/ep4.webp"),
  "s2/ep5": require("@/assets/images/episodes/s2/ep5.webp"),
  "s2/ep6": require("@/assets/images/episodes/s2/ep6.webp"),
  "s2/ep7": require("@/assets/images/episodes/s2/ep7.webp"),
  "s2/ep8": require("@/assets/images/episodes/s2/ep8.webp"),
  "s2/ep9": require("@/assets/images/episodes/s2/ep9.webp"),
  "s2/ep10": require("@/assets/images/episodes/s2/ep10.webp"),
  "s2/ep11": require("@/assets/images/episodes/s2/ep11.webp"),
  "s2/ep12": require("@/assets/images/episodes/s2/ep12.webp"),
  "s2/ep13": require("@/assets/images/episodes/s2/ep13.webp"),
  "s2/ep14": require("@/assets/images/episodes/s2/ep14.webp"),
  "s2/ep15": require("@/assets/images/episodes/s2/ep15.webp"),

  // Season 3
  "s3/ep1": require("@/assets/images/episodes/s3/ep1.webp"),
  "s3/ep2": require("@/assets/images/episodes/s3/ep2.webp"),
  "s3/ep3": require("@/assets/images/episodes/s3/ep3.webp"),
  "s3/ep4": require("@/assets/images/episodes/s3/ep4.webp"),
  "s3/ep5": require("@/assets/images/episodes/s3/ep5.webp"),
  "s3/ep6": require("@/assets/images/episodes/s3/ep6.webp"),
  "s3/ep7": require("@/assets/images/episodes/s3/ep7.webp"),
  "s3/ep8": require("@/assets/images/episodes/s3/ep8.webp"),
  "s3/ep9": require("@/assets/images/episodes/s3/ep9.webp"),
  "s3/ep10": require("@/assets/images/episodes/s3/ep10.webp"),
  "s3/ep11": require("@/assets/images/episodes/s3/ep11.webp"),
  "s3/ep12": require("@/assets/images/episodes/s3/ep12.webp"),
  "s3/ep13": require("@/assets/images/episodes/s3/ep13.webp"),
  "s3/ep14": require("@/assets/images/episodes/s3/ep14.webp"),
  "s3/ep15": require("@/assets/images/episodes/s3/ep15.webp"),

  // Season 4
  "s4/ep1": require("@/assets/images/episodes/s4/ep1.webp"),
  "s4/ep2": require("@/assets/images/episodes/s4/ep2.webp"),
  "s4/ep3": require("@/assets/images/episodes/s4/ep3.webp"),
  "s4/ep4": require("@/assets/images/episodes/s4/ep4.webp"),
  "s4/ep5": require("@/assets/images/episodes/s4/ep5.webp"),
  "s4/ep6": require("@/assets/images/episodes/s4/ep6.webp"),
  "s4/ep7": require("@/assets/images/episodes/s4/ep7.webp"),
  "s4/ep8": require("@/assets/images/episodes/s4/ep8.webp"),
  "s4/ep9": require("@/assets/images/episodes/s4/ep9.webp"),
  "s4/ep10": require("@/assets/images/episodes/s4/ep10.webp"),
  "s4/ep11": require("@/assets/images/episodes/s4/ep11.webp"),
  "s4/ep12": require("@/assets/images/episodes/s4/ep12.webp"),
  "s4/ep13": require("@/assets/images/episodes/s4/ep13.webp"),
  "s4/ep14": require("@/assets/images/episodes/s4/ep14.webp"),
  "s4/ep15": require("@/assets/images/episodes/s4/ep15.webp"),

  // Season 5
  "s5/ep1": require("@/assets/images/episodes/s5/ep1.webp"),
  "s5/ep2": require("@/assets/images/episodes/s5/ep2.webp"),
  "s5/ep3": require("@/assets/images/episodes/s5/ep3.webp"),
  "s5/ep4": require("@/assets/images/episodes/s5/ep4.webp"),
  "s5/ep5": require("@/assets/images/episodes/s5/ep5.webp"),
  "s5/ep6": require("@/assets/images/episodes/s5/ep6.webp"),
  "s5/ep7": require("@/assets/images/episodes/s5/ep7.webp"),
  "s5/ep8": require("@/assets/images/episodes/s5/ep8.webp"),
  "s5/ep9": require("@/assets/images/episodes/s5/ep9.webp"),
  "s5/ep10": require("@/assets/images/episodes/s5/ep10.webp"),
  "s5/ep11": require("@/assets/images/episodes/s5/ep11.webp"),
  "s5/ep12": require("@/assets/images/episodes/s5/ep12.webp"),
  "s5/ep13": require("@/assets/images/episodes/s5/ep13.webp"),
  "s5/ep14": require("@/assets/images/episodes/s5/ep14.webp"),
  "s5/ep15": require("@/assets/images/episodes/s5/ep15.webp"),

  // Season 6
  "s6/ep1": require("@/assets/images/episodes/s6/ep1.webp"),
  "s6/ep2": require("@/assets/images/episodes/s6/ep2.webp"),
  "s6/ep3": require("@/assets/images/episodes/s6/ep3.webp"),
  "s6/ep4": require("@/assets/images/episodes/s6/ep4.webp"),
  "s6/ep5": require("@/assets/images/episodes/s6/ep5.webp"),
  "s6/ep6": require("@/assets/images/episodes/s6/ep6.webp"),
  "s6/ep7": require("@/assets/images/episodes/s6/ep7.webp"),
  "s6/ep8": require("@/assets/images/episodes/s6/ep8.webp"),
  "s6/ep9": require("@/assets/images/episodes/s6/ep9.webp"),
  "s6/ep10": require("@/assets/images/episodes/s6/ep10.webp"),
  "s6/ep11": require("@/assets/images/episodes/s6/ep11.webp"),
  "s6/ep12": require("@/assets/images/episodes/s6/ep12.webp"),
  "s6/ep13": require("@/assets/images/episodes/s6/ep13.webp"),
  "s6/ep14": require("@/assets/images/episodes/s6/ep14.webp"),
  "s6/ep15": require("@/assets/images/episodes/s6/ep15.webp"),

  // Season 7
  "s7/ep1": require("@/assets/images/episodes/s7/ep1.webp"),
  "s7/ep2": require("@/assets/images/episodes/s7/ep2.webp"),
  "s7/ep3": require("@/assets/images/episodes/s7/ep3.webp"),
  "s7/ep4": require("@/assets/images/episodes/s7/ep4.webp"),
  "s7/ep5": require("@/assets/images/episodes/s7/ep5.webp"),
  "s7/ep6": require("@/assets/images/episodes/s7/ep6.webp"),
  "s7/ep7": require("@/assets/images/episodes/s7/ep7.webp"),
  "s7/ep8": require("@/assets/images/episodes/s7/ep8.webp"),
  "s7/ep9": require("@/assets/images/episodes/s7/ep9.webp"),
  "s7/ep10": require("@/assets/images/episodes/s7/ep10.webp"),
  "s7/ep11": require("@/assets/images/episodes/s7/ep11.webp"),
  "s7/ep12": require("@/assets/images/episodes/s7/ep12.webp"),
  "s7/ep13": require("@/assets/images/episodes/s7/ep13.webp"),
  "s7/ep14": require("@/assets/images/episodes/s7/ep14.webp"),
  "s7/ep15": require("@/assets/images/episodes/s7/ep15.webp"),

  // Season 8
  "s8/ep1": require("@/assets/images/episodes/s8/ep1.webp"),
  "s8/ep2": require("@/assets/images/episodes/s8/ep2.webp"),
  "s8/ep3": require("@/assets/images/episodes/s8/ep3.webp"),
  "s8/ep4": require("@/assets/images/episodes/s8/ep4.webp"),
  "s8/ep5": require("@/assets/images/episodes/s8/ep5.webp"),
  "s8/ep6": require("@/assets/images/episodes/s8/ep6.webp"),
  "s8/ep7": require("@/assets/images/episodes/s8/ep7.webp"),
  "s8/ep8": require("@/assets/images/episodes/s8/ep8.webp"),
  "s8/ep9": require("@/assets/images/episodes/s8/ep9.webp"),
  "s8/ep10": require("@/assets/images/episodes/s8/ep10.webp"),
  "s8/ep11": require("@/assets/images/episodes/s8/ep11.webp"),
  "s8/ep12": require("@/assets/images/episodes/s8/ep12.webp"),
  "s8/ep13": require("@/assets/images/episodes/s8/ep13.webp"),
  "s8/ep14": require("@/assets/images/episodes/s8/ep14.webp"),
  "s8/ep15": require("@/assets/images/episodes/s8/ep15.webp"),

  // Season 9
  "s9/ep1": require("@/assets/images/episodes/s9/ep1.webp"),
  "s9/ep2": require("@/assets/images/episodes/s9/ep2.webp"),
  "s9/ep3": require("@/assets/images/episodes/s9/ep3.webp"),
  "s9/ep4": require("@/assets/images/episodes/s9/ep4.webp"),
  "s9/ep5": require("@/assets/images/episodes/s9/ep5.webp"),
  "s9/ep6": require("@/assets/images/episodes/s9/ep6.webp"),
  "s9/ep7": require("@/assets/images/episodes/s9/ep7.webp"),
  "s9/ep8": require("@/assets/images/episodes/s9/ep8.webp"),
  "s9/ep9": require("@/assets/images/episodes/s9/ep9.webp"),
  "s9/ep10": require("@/assets/images/episodes/s9/ep10.webp"),
  "s9/ep11": require("@/assets/images/episodes/s9/ep11.webp"),
  "s9/ep12": require("@/assets/images/episodes/s9/ep12.webp"),
  "s9/ep13": require("@/assets/images/episodes/s9/ep13.webp"),
  "s9/ep14": require("@/assets/images/episodes/s9/ep14.webp"),
  "s9/ep15": require("@/assets/images/episodes/s9/ep15.webp"),

  // Season 10
  "s10/ep1": require("@/assets/images/episodes/s10/ep1.webp"),
  "s10/ep2": require("@/assets/images/episodes/s10/ep2.webp"),
  "s10/ep3": require("@/assets/images/episodes/s10/ep3.webp"),
  "s10/ep4": require("@/assets/images/episodes/s10/ep4.webp"),
  "s10/ep5": require("@/assets/images/episodes/s10/ep5.webp"),
  "s10/ep6": require("@/assets/images/episodes/s10/ep6.webp"),
  "s10/ep7": require("@/assets/images/episodes/s10/ep7.webp"),
  "s10/ep8": require("@/assets/images/episodes/s10/ep8.webp"),
  "s10/ep9": require("@/assets/images/episodes/s10/ep9.webp"),
  "s10/ep10": require("@/assets/images/episodes/s10/ep10.webp"),
  "s10/ep11": require("@/assets/images/episodes/s10/ep11.webp"),
  "s10/ep12": require("@/assets/images/episodes/s10/ep12.webp"),
  "s10/ep13": require("@/assets/images/episodes/s10/ep13.webp"),
  "s10/ep14": require("@/assets/images/episodes/s10/ep14.webp"),
  "s10/ep15": require("@/assets/images/episodes/s10/ep15.webp"),

  // Season 11
  "s11/ep1": require("@/assets/images/episodes/s11/ep1.webp"),
  "s11/ep2": require("@/assets/images/episodes/s11/ep2.webp"),
  "s11/ep3": require("@/assets/images/episodes/s11/ep3.webp"),
  "s11/ep4": require("@/assets/images/episodes/s11/ep4.webp"),
  "s11/ep5": require("@/assets/images/episodes/s11/ep5.webp"),
  "s11/ep6": require("@/assets/images/episodes/s11/ep6.webp"),
  "s11/ep7": require("@/assets/images/episodes/s11/ep7.webp"),
  "s11/ep8": require("@/assets/images/episodes/s11/ep8.webp"),
  "s11/ep9": require("@/assets/images/episodes/s11/ep9.webp"),
  "s11/ep10": require("@/assets/images/episodes/s11/ep10.webp"),
  "s11/ep11": require("@/assets/images/episodes/s11/ep11.webp"),
  "s11/ep12": require("@/assets/images/episodes/s11/ep12.webp"),
  "s11/ep13": require("@/assets/images/episodes/s11/ep13.webp"),
  "s11/ep14": require("@/assets/images/episodes/s11/ep14.webp"),
  "s11/ep15": require("@/assets/images/episodes/s11/ep15.webp"),

  // Season 12
  "s12/ep1": require("@/assets/images/episodes/s12/ep1.webp"),
  "s12/ep2": require("@/assets/images/episodes/s12/ep2.webp"),
  "s12/ep3": require("@/assets/images/episodes/s12/ep3.webp"),
  "s12/ep4": require("@/assets/images/episodes/s12/ep4.webp"),
  "s12/ep5": require("@/assets/images/episodes/s12/ep5.webp"),
  "s12/ep6": require("@/assets/images/episodes/s12/ep6.webp"),
  "s12/ep7": require("@/assets/images/episodes/s12/ep7.webp"),
  "s12/ep8": require("@/assets/images/episodes/s12/ep8.webp"),
  "s12/ep9": require("@/assets/images/episodes/s12/ep9.webp"),
  "s12/ep10": require("@/assets/images/episodes/s12/ep10.webp"),
  "s12/ep11": require("@/assets/images/episodes/s12/ep11.webp"),
  "s12/ep12": require("@/assets/images/episodes/s12/ep12.webp"),
  "s12/ep13": require("@/assets/images/episodes/s12/ep13.webp"),
  "s12/ep14": require("@/assets/images/episodes/s12/ep14.webp"),
  "s12/ep15": require("@/assets/images/episodes/s12/ep15.webp"),

  // Season 13
  "s13/ep1": require("@/assets/images/episodes/s13/ep1.webp"),
  "s13/ep2": require("@/assets/images/episodes/s13/ep2.webp"),
  "s13/ep3": require("@/assets/images/episodes/s13/ep3.webp"),
  "s13/ep4": require("@/assets/images/episodes/s13/ep4.webp"),
  "s13/ep5": require("@/assets/images/episodes/s13/ep5.webp"),
  "s13/ep6": require("@/assets/images/episodes/s13/ep6.webp"),
  "s13/ep7": require("@/assets/images/episodes/s13/ep7.webp"),
  "s13/ep8": require("@/assets/images/episodes/s13/ep8.webp"),
  "s13/ep9": require("@/assets/images/episodes/s13/ep9.webp"),
  "s13/ep10": require("@/assets/images/episodes/s13/ep10.webp"),
  "s13/ep11": require("@/assets/images/episodes/s13/ep11.webp"),
  "s13/ep12": require("@/assets/images/episodes/s13/ep12.webp"),
  "s13/ep13": require("@/assets/images/episodes/s13/ep13.webp"),
  "s13/ep14": require("@/assets/images/episodes/s13/ep14.webp"),
  "s13/ep15": require("@/assets/images/episodes/s13/ep15.webp"),

  // Season 14
  "s14/ep1": require("@/assets/images/episodes/s14/ep1.webp"),
  "s14/ep2": require("@/assets/images/episodes/s14/ep2.webp"),
  "s14/ep3": require("@/assets/images/episodes/s14/ep3.webp"),
  "s14/ep4": require("@/assets/images/episodes/s14/ep4.webp"),
  "s14/ep5": require("@/assets/images/episodes/s14/ep5.webp"),
  "s14/ep6": require("@/assets/images/episodes/s14/ep6.webp"),
  "s14/ep7": require("@/assets/images/episodes/s14/ep7.webp"),
  "s14/ep8": require("@/assets/images/episodes/s14/ep8.webp"),
  "s14/ep9": require("@/assets/images/episodes/s14/ep9.webp"),
  "s14/ep10": require("@/assets/images/episodes/s14/ep10.webp"),
  "s14/ep11": require("@/assets/images/episodes/s14/ep11.webp"),
  "s14/ep12": require("@/assets/images/episodes/s14/ep12.webp"),
  "s14/ep13": require("@/assets/images/episodes/s14/ep13.webp"),
  "s14/ep14": require("@/assets/images/episodes/s14/ep14.webp"),
  "s14/ep15": require("@/assets/images/episodes/s14/ep15.webp"),

  // Season 15
  "s15/ep1": require("@/assets/images/episodes/s15/ep1.webp"),
  "s15/ep2": require("@/assets/images/episodes/s15/ep2.webp"),
  "s15/ep3": require("@/assets/images/episodes/s15/ep3.webp"),
  "s15/ep4": require("@/assets/images/episodes/s15/ep4.webp"),
  "s15/ep5": require("@/assets/images/episodes/s15/ep5.webp"),
  "s15/ep6": require("@/assets/images/episodes/s15/ep6.webp"),
  "s15/ep7": require("@/assets/images/episodes/s15/ep7.webp"),
  "s15/ep8": require("@/assets/images/episodes/s15/ep8.webp"),
  "s15/ep9": require("@/assets/images/episodes/s15/ep9.webp"),
  "s15/ep10": require("@/assets/images/episodes/s15/ep10.webp"),
  "s15/ep11": require("@/assets/images/episodes/s15/ep11.webp"),
  "s15/ep12": require("@/assets/images/episodes/s15/ep12.webp"),
  "s15/ep13": require("@/assets/images/episodes/s15/ep13.webp"),
  "s15/ep14": require("@/assets/images/episodes/s15/ep14.webp"),
  "s15/ep15": require("@/assets/images/episodes/s15/ep15.webp"),

  // Season 16
  "s16/ep1": require("@/assets/images/episodes/s16/ep1.webp"),
  "s16/ep2": require("@/assets/images/episodes/s16/ep2.webp"),
  "s16/ep3": require("@/assets/images/episodes/s16/ep3.webp"),
  "s16/ep4": require("@/assets/images/episodes/s16/ep4.webp"),
  "s16/ep5": require("@/assets/images/episodes/s16/ep5.webp"),
  "s16/ep6": require("@/assets/images/episodes/s16/ep6.webp"),
  "s16/ep7": require("@/assets/images/episodes/s16/ep7.webp"),
  "s16/ep8": require("@/assets/images/episodes/s16/ep8.webp"),
  "s16/ep9": require("@/assets/images/episodes/s16/ep9.webp"),
  "s16/ep10": require("@/assets/images/episodes/s16/ep10.webp"),
  "s16/ep11": require("@/assets/images/episodes/s16/ep11.webp"),
  "s16/ep12": require("@/assets/images/episodes/s16/ep12.webp"),
  "s16/ep13": require("@/assets/images/episodes/s16/ep13.webp"),
  "s16/ep14": require("@/assets/images/episodes/s16/ep14.webp"),
  "s16/ep15": require("@/assets/images/episodes/s16/ep15.webp"),

  // Season 17
  "s17/ep1": require("@/assets/images/episodes/s17/ep1.webp"),
  "s17/ep2": require("@/assets/images/episodes/s17/ep2.webp"),
  "s17/ep3": require("@/assets/images/episodes/s17/ep3.webp"),
  "s17/ep4": require("@/assets/images/episodes/s17/ep4.webp"),
  "s17/ep5": require("@/assets/images/episodes/s17/ep5.webp"),
  "s17/ep6": require("@/assets/images/episodes/s17/ep6.webp"),
  "s17/ep7": require("@/assets/images/episodes/s17/ep7.webp"),
  "s17/ep8": require("@/assets/images/episodes/s17/ep8.webp"),
  "s17/ep9": require("@/assets/images/episodes/s17/ep9.webp"),
  "s17/ep10": require("@/assets/images/episodes/s17/ep10.webp"),
  "s17/ep11": require("@/assets/images/episodes/s17/ep11.webp"),
  "s17/ep12": require("@/assets/images/episodes/s17/ep12.webp"),
  "s17/ep13": require("@/assets/images/episodes/s17/ep13.webp"),
  "s17/ep14": require("@/assets/images/episodes/s17/ep14.webp"),
  "s17/ep15": require("@/assets/images/episodes/s17/ep15.webp"),

  // Season 18
  "s18/ep1": require("@/assets/images/episodes/s18/ep1.webp"),
  "s18/ep2": require("@/assets/images/episodes/s18/ep2.webp"),
  "s18/ep3": require("@/assets/images/episodes/s18/ep3.webp"),
  "s18/ep4": require("@/assets/images/episodes/s18/ep4.webp"),
  "s18/ep5": require("@/assets/images/episodes/s18/ep5.webp"),
  "s18/ep6": require("@/assets/images/episodes/s18/ep6.webp"),
  "s18/ep7": require("@/assets/images/episodes/s18/ep7.webp"),
  "s18/ep8": require("@/assets/images/episodes/s18/ep8.webp"),
  "s18/ep9": require("@/assets/images/episodes/s18/ep9.webp"),
  "s18/ep10": require("@/assets/images/episodes/s18/ep10.webp"),
  "s18/ep11": require("@/assets/images/episodes/s18/ep11.webp"),
  "s18/ep12": require("@/assets/images/episodes/s18/ep12.webp"),
  "s18/ep13": require("@/assets/images/episodes/s18/ep13.webp"),
  "s18/ep14": require("@/assets/images/episodes/s18/ep14.webp"),
  "s18/ep15": require("@/assets/images/episodes/s18/ep15.webp"),

  // Season 19
  "s19/ep1": require("@/assets/images/episodes/s19/ep1.webp"),
  "s19/ep2": require("@/assets/images/episodes/s19/ep2.webp"),
  "s19/ep3": require("@/assets/images/episodes/s19/ep3.webp"),
  "s19/ep4": require("@/assets/images/episodes/s19/ep4.webp"),
  "s19/ep5": require("@/assets/images/episodes/s19/ep5.webp"),
  "s19/ep6": require("@/assets/images/episodes/s19/ep6.webp"),
  "s19/ep7": require("@/assets/images/episodes/s19/ep7.webp"),
  "s19/ep8": require("@/assets/images/episodes/s19/ep8.webp"),
  "s19/ep9": require("@/assets/images/episodes/s19/ep9.webp"),
  "s19/ep10": require("@/assets/images/episodes/s19/ep10.webp"),
  "s19/ep11": require("@/assets/images/episodes/s19/ep11.webp"),
  "s19/ep12": require("@/assets/images/episodes/s19/ep12.webp"),
  "s19/ep13": require("@/assets/images/episodes/s19/ep13.webp"),
  "s19/ep14": require("@/assets/images/episodes/s19/ep14.webp"),
  "s19/ep15": require("@/assets/images/episodes/s19/ep15.webp"),

  // Season 20
  "s20/ep1": require("@/assets/images/episodes/s20/ep1.webp"),
  "s20/ep2": require("@/assets/images/episodes/s20/ep2.webp"),
  "s20/ep3": require("@/assets/images/episodes/s20/ep3.webp"),
  "s20/ep4": require("@/assets/images/episodes/s20/ep4.webp"),
  "s20/ep5": require("@/assets/images/episodes/s20/ep5.webp"),
  "s20/ep6": require("@/assets/images/episodes/s20/ep6.webp"),
  "s20/ep7": require("@/assets/images/episodes/s20/ep7.webp"),
  "s20/ep8": require("@/assets/images/episodes/s20/ep8.webp"),
  "s20/ep9": require("@/assets/images/episodes/s20/ep9.webp"),
  "s20/ep10": require("@/assets/images/episodes/s20/ep10.webp"),
  "s20/ep11": require("@/assets/images/episodes/s20/ep11.webp"),
  "s20/ep12": require("@/assets/images/episodes/s20/ep12.webp"),
  "s20/ep13": require("@/assets/images/episodes/s20/ep13.webp"),
  "s20/ep14": require("@/assets/images/episodes/s20/ep14.webp"),
  "s20/ep15": require("@/assets/images/episodes/s20/ep15.webp"),

  // Season 21
  "s21/ep1": require("@/assets/images/episodes/s21/ep1.webp"),
  "s21/ep2": require("@/assets/images/episodes/s21/ep2.webp"),
  "s21/ep3": require("@/assets/images/episodes/s21/ep3.webp"),
  "s21/ep4": require("@/assets/images/episodes/s21/ep4.webp"),
  "s21/ep5": require("@/assets/images/episodes/s21/ep5.webp"),
  "s21/ep6": require("@/assets/images/episodes/s21/ep6.webp"),
  "s21/ep7": require("@/assets/images/episodes/s21/ep7.webp"),
  "s21/ep8": require("@/assets/images/episodes/s21/ep8.webp"),
  "s21/ep9": require("@/assets/images/episodes/s21/ep9.webp"),
  "s21/ep10": require("@/assets/images/episodes/s21/ep10.webp"),
  "s21/ep11": require("@/assets/images/episodes/s21/ep11.webp"),
  "s21/ep12": require("@/assets/images/episodes/s21/ep12.webp"),
  "s21/ep13": require("@/assets/images/episodes/s21/ep13.webp"),
  "s21/ep14": require("@/assets/images/episodes/s21/ep14.webp"),
  "s21/ep15": require("@/assets/images/episodes/s21/ep15.webp"),

  // Season 22
  "s22/ep1": require("@/assets/images/episodes/s22/ep1.webp"),
  "s22/ep2": require("@/assets/images/episodes/s22/ep2.webp"),
  "s22/ep3": require("@/assets/images/episodes/s22/ep3.webp"),
  "s22/ep4": require("@/assets/images/episodes/s22/ep4.webp"),
  "s22/ep5": require("@/assets/images/episodes/s22/ep5.webp"),
  "s22/ep6": require("@/assets/images/episodes/s22/ep6.webp"),
  "s22/ep7": require("@/assets/images/episodes/s22/ep7.webp"),
  "s22/ep8": require("@/assets/images/episodes/s22/ep8.webp"),
  "s22/ep9": require("@/assets/images/episodes/s22/ep9.webp"),
  "s22/ep10": require("@/assets/images/episodes/s22/ep10.webp"),
  "s22/ep11": require("@/assets/images/episodes/s22/ep11.webp"),
  "s22/ep12": require("@/assets/images/episodes/s22/ep12.webp"),
  "s22/ep13": require("@/assets/images/episodes/s22/ep13.webp"),
  "s22/ep14": require("@/assets/images/episodes/s22/ep14.webp"),
  "s22/ep15": require("@/assets/images/episodes/s22/ep15.webp"),

  // Season 23
  "s23/ep1": require("@/assets/images/episodes/s23/ep1.webp"),
  "s23/ep2": require("@/assets/images/episodes/s23/ep2.webp"),
  "s23/ep3": require("@/assets/images/episodes/s23/ep3.webp"),
  "s23/ep4": require("@/assets/images/episodes/s23/ep4.webp"),
  "s23/ep5": require("@/assets/images/episodes/s23/ep5.webp"),
  "s23/ep6": require("@/assets/images/episodes/s23/ep6.webp"),
  "s23/ep7": require("@/assets/images/episodes/s23/ep7.webp"),
  "s23/ep8": require("@/assets/images/episodes/s23/ep8.webp"),
  "s23/ep9": require("@/assets/images/episodes/s23/ep9.webp"),
  "s23/ep10": require("@/assets/images/episodes/s23/ep10.webp"),
  "s23/ep11": require("@/assets/images/episodes/s23/ep11.webp"),
  "s23/ep12": require("@/assets/images/episodes/s23/ep12.webp"),
  "s23/ep13": require("@/assets/images/episodes/s23/ep13.webp"),
  "s23/ep14": require("@/assets/images/episodes/s23/ep14.webp"),
  "s23/ep15": require("@/assets/images/episodes/s23/ep15.webp"),

  // Season 24
  "s24/ep1": require("@/assets/images/episodes/s24/ep1.webp"),
  "s24/ep2": require("@/assets/images/episodes/s24/ep2.webp"),
  "s24/ep3": require("@/assets/images/episodes/s24/ep3.webp"),
  "s24/ep4": require("@/assets/images/episodes/s24/ep4.webp"),
  "s24/ep5": require("@/assets/images/episodes/s24/ep5.webp"),
  "s24/ep6": require("@/assets/images/episodes/s24/ep6.webp"),
  "s24/ep7": require("@/assets/images/episodes/s24/ep7.webp"),
  "s24/ep8": require("@/assets/images/episodes/s24/ep8.webp"),
  "s24/ep9": require("@/assets/images/episodes/s24/ep9.webp"),
  "s24/ep10": require("@/assets/images/episodes/s24/ep10.webp"),
  "s24/ep11": require("@/assets/images/episodes/s24/ep11.webp"),
  "s24/ep12": require("@/assets/images/episodes/s24/ep12.webp"),
  "s24/ep13": require("@/assets/images/episodes/s24/ep13.webp"),
  "s24/ep14": require("@/assets/images/episodes/s24/ep14.webp"),
  "s24/ep15": require("@/assets/images/episodes/s24/ep15.webp"),

  // Season 25
  "s25/ep1": require("@/assets/images/episodes/s25/ep1.webp"),
  "s25/ep2": require("@/assets/images/episodes/s25/ep2.webp"),
  "s25/ep3": require("@/assets/images/episodes/s25/ep3.webp"),
  "s25/ep4": require("@/assets/images/episodes/s25/ep4.webp"),
  "s25/ep5": require("@/assets/images/episodes/s25/ep5.webp"),
  "s25/ep6": require("@/assets/images/episodes/s25/ep6.webp"),
  "s25/ep7": require("@/assets/images/episodes/s25/ep7.webp"),
  "s25/ep8": require("@/assets/images/episodes/s25/ep8.webp"),
  "s25/ep9": require("@/assets/images/episodes/s25/ep9.webp"),
  "s25/ep10": require("@/assets/images/episodes/s25/ep10.webp"),
  "s25/ep11": require("@/assets/images/episodes/s25/ep11.webp"),
  "s25/ep12": require("@/assets/images/episodes/s25/ep12.webp"),
  "s25/ep13": require("@/assets/images/episodes/s25/ep13.webp"),
  "s25/ep14": require("@/assets/images/episodes/s25/ep14.webp"),
  "s25/ep15": require("@/assets/images/episodes/s25/ep15.webp"),

  // Season 26
  "s26/ep1": require("@/assets/images/episodes/s26/ep1.webp"),
  "s26/ep2": require("@/assets/images/episodes/s26/ep2.webp"),
  "s26/ep3": require("@/assets/images/episodes/s26/ep3.webp"),
  "s26/ep4": require("@/assets/images/episodes/s26/ep4.webp"),
  "s26/ep5": require("@/assets/images/episodes/s26/ep5.webp"),
  "s26/ep6": require("@/assets/images/episodes/s26/ep6.webp"),
  "s26/ep7": require("@/assets/images/episodes/s26/ep7.webp"),
  "s26/ep8": require("@/assets/images/episodes/s26/ep8.webp"),
  "s26/ep9": require("@/assets/images/episodes/s26/ep9.webp"),
  "s26/ep10": require("@/assets/images/episodes/s26/ep10.webp"),
  "s26/ep11": require("@/assets/images/episodes/s26/ep11.webp"),
  "s26/ep12": require("@/assets/images/episodes/s26/ep12.webp"),
  "s26/ep13": require("@/assets/images/episodes/s26/ep13.webp"),
  "s26/ep14": require("@/assets/images/episodes/s26/ep14.webp"),
  "s26/ep15": require("@/assets/images/episodes/s26/ep15.webp"),

  // Season 27
  "s27/ep1": require("@/assets/images/episodes/s27/ep1.webp"),
  "s27/ep2": require("@/assets/images/episodes/s27/ep2.webp"),
  "s27/ep3": require("@/assets/images/episodes/s27/ep3.webp"),
  "s27/ep4": require("@/assets/images/episodes/s27/ep4.webp"),
  "s27/ep5": require("@/assets/images/episodes/s27/ep5.webp"),
  "s27/ep6": require("@/assets/images/episodes/s27/ep6.webp"),
  "s27/ep7": require("@/assets/images/episodes/s27/ep7.webp"),
  "s27/ep8": require("@/assets/images/episodes/s27/ep8.webp"),
  "s27/ep9": require("@/assets/images/episodes/s27/ep9.webp"),
  "s27/ep10": require("@/assets/images/episodes/s27/ep10.webp"),
  "s27/ep11": require("@/assets/images/episodes/s27/ep11.webp"),
  "s27/ep12": require("@/assets/images/episodes/s27/ep12.webp"),
  "s27/ep13": require("@/assets/images/episodes/s27/ep13.webp"),
  "s27/ep14": require("@/assets/images/episodes/s27/ep14.webp"),
  "s27/ep15": require("@/assets/images/episodes/s27/ep15.webp"),

  // Season 28
  "s28/ep1": require("@/assets/images/episodes/s28/ep1.webp"),
  "s28/ep2": require("@/assets/images/episodes/s28/ep2.webp"),
  "s28/ep3": require("@/assets/images/episodes/s28/ep3.webp"),
  "s28/ep4": require("@/assets/images/episodes/s28/ep4.webp"),
  "s28/ep5": require("@/assets/images/episodes/s28/ep5.webp"),
  "s28/ep6": require("@/assets/images/episodes/s28/ep6.webp"),
  "s28/ep7": require("@/assets/images/episodes/s28/ep7.webp"),
  "s28/ep8": require("@/assets/images/episodes/s28/ep8.webp"),
  "s28/ep9": require("@/assets/images/episodes/s28/ep9.webp"),
  "s28/ep10": require("@/assets/images/episodes/s28/ep10.webp"),
  "s28/ep11": require("@/assets/images/episodes/s28/ep11.webp"),
  "s28/ep12": require("@/assets/images/episodes/s28/ep12.webp"),
  "s28/ep13": require("@/assets/images/episodes/s28/ep13.webp"),
  "s28/ep14": require("@/assets/images/episodes/s28/ep14.webp"),
  "s28/ep15": require("@/assets/images/episodes/s28/ep15.webp"),

  // Season 29
  "s29/ep1": require("@/assets/images/episodes/s29/ep1.webp"),
  "s29/ep2": require("@/assets/images/episodes/s29/ep2.webp"),
  "s29/ep3": require("@/assets/images/episodes/s29/ep3.webp"),
  "s29/ep4": require("@/assets/images/episodes/s29/ep4.webp"),
  "s29/ep5": require("@/assets/images/episodes/s29/ep5.webp"),
  "s29/ep6": require("@/assets/images/episodes/s29/ep6.webp"),
  "s29/ep7": require("@/assets/images/episodes/s29/ep7.webp"),
  "s29/ep8": require("@/assets/images/episodes/s29/ep8.webp"),
  "s29/ep9": require("@/assets/images/episodes/s29/ep9.webp"),
  "s29/ep10": require("@/assets/images/episodes/s29/ep10.webp"),
  "s29/ep11": require("@/assets/images/episodes/s29/ep11.webp"),
  "s29/ep12": require("@/assets/images/episodes/s29/ep12.webp"),
  "s29/ep13": require("@/assets/images/episodes/s29/ep13.webp"),
  "s29/ep14": require("@/assets/images/episodes/s29/ep14.webp"),
  "s29/ep15": require("@/assets/images/episodes/s29/ep15.webp"),

  // Season 30
  "s30/ep1": require("@/assets/images/episodes/s30/ep1.webp"),
  "s30/ep2": require("@/assets/images/episodes/s30/ep2.webp"),
  "s30/ep3": require("@/assets/images/episodes/s30/ep3.webp"),
  "s30/ep4": require("@/assets/images/episodes/s30/ep4.webp"),
  "s30/ep5": require("@/assets/images/episodes/s30/ep5.webp"),
  "s30/ep6": require("@/assets/images/episodes/s30/ep6.webp"),
  "s30/ep7": require("@/assets/images/episodes/s30/ep7.webp"),
  "s30/ep8": require("@/assets/images/episodes/s30/ep8.webp"),
  "s30/ep9": require("@/assets/images/episodes/s30/ep9.webp"),
  "s30/ep10": require("@/assets/images/episodes/s30/ep10.webp"),
  "s30/ep11": require("@/assets/images/episodes/s30/ep11.webp"),
  "s30/ep12": require("@/assets/images/episodes/s30/ep12.webp"),
  "s30/ep13": require("@/assets/images/episodes/s30/ep13.webp"),
  "s30/ep14": require("@/assets/images/episodes/s30/ep14.webp"),
  "s30/ep15": require("@/assets/images/episodes/s30/ep15.webp"),

  // Season 31
  "s31/ep1": require("@/assets/images/episodes/s31/ep1.webp"),
  "s31/ep2": require("@/assets/images/episodes/s31/ep2.webp"),
  "s31/ep3": require("@/assets/images/episodes/s31/ep3.webp"),
  "s31/ep4": require("@/assets/images/episodes/s31/ep4.webp"),
  "s31/ep5": require("@/assets/images/episodes/s31/ep5.webp"),
  "s31/ep6": require("@/assets/images/episodes/s31/ep6.webp"),
  "s31/ep7": require("@/assets/images/episodes/s31/ep7.webp"),
  "s31/ep8": require("@/assets/images/episodes/s31/ep8.webp"),
  "s31/ep9": require("@/assets/images/episodes/s31/ep9.webp"),
  "s31/ep10": require("@/assets/images/episodes/s31/ep10.webp"),
  "s31/ep11": require("@/assets/images/episodes/s31/ep11.webp"),
  "s31/ep12": require("@/assets/images/episodes/s31/ep12.webp"),
  "s31/ep13": require("@/assets/images/episodes/s31/ep13.webp"),
  "s31/ep14": require("@/assets/images/episodes/s31/ep14.webp"),
  "s31/ep15": require("@/assets/images/episodes/s31/ep15.webp"),

  // Season 32
  "s32/ep1": require("@/assets/images/episodes/s32/ep1.webp"),
  "s32/ep2": require("@/assets/images/episodes/s32/ep2.webp"),
  "s32/ep3": require("@/assets/images/episodes/s32/ep3.webp"),
  "s32/ep4": require("@/assets/images/episodes/s32/ep4.webp"),
  "s32/ep5": require("@/assets/images/episodes/s32/ep5.webp"),
  "s32/ep6": require("@/assets/images/episodes/s32/ep6.webp"),
  "s32/ep7": require("@/assets/images/episodes/s32/ep7.webp"),
  "s32/ep8": require("@/assets/images/episodes/s32/ep8.webp"),
  "s32/ep9": require("@/assets/images/episodes/s32/ep9.webp"),
  "s32/ep10": require("@/assets/images/episodes/s32/ep10.webp"),
  "s32/ep11": require("@/assets/images/episodes/s32/ep11.webp"),
  "s32/ep12": require("@/assets/images/episodes/s32/ep12.webp"),
  "s32/ep13": require("@/assets/images/episodes/s32/ep13.webp"),
  "s32/ep14": require("@/assets/images/episodes/s32/ep14.webp"),
  "s32/ep15": require("@/assets/images/episodes/s32/ep15.webp"),

  // Season 33
  "s33/ep1": require("@/assets/images/episodes/s33/ep1.webp"),
  "s33/ep2": require("@/assets/images/episodes/s33/ep2.webp"),
  "s33/ep3": require("@/assets/images/episodes/s33/ep3.webp"),
  "s33/ep4": require("@/assets/images/episodes/s33/ep4.webp"),
  "s33/ep5": require("@/assets/images/episodes/s33/ep5.webp"),
  "s33/ep6": require("@/assets/images/episodes/s33/ep6.webp"),
  "s33/ep7": require("@/assets/images/episodes/s33/ep7.webp"),
  "s33/ep8": require("@/assets/images/episodes/s33/ep8.webp"),
  "s33/ep9": require("@/assets/images/episodes/s33/ep9.webp"),
  "s33/ep10": require("@/assets/images/episodes/s33/ep10.webp"),
  "s33/ep11": require("@/assets/images/episodes/s33/ep11.webp"),
  "s33/ep12": require("@/assets/images/episodes/s33/ep12.webp"),
  "s33/ep13": require("@/assets/images/episodes/s33/ep13.webp"),
  "s33/ep14": require("@/assets/images/episodes/s33/ep14.webp"),
  "s33/ep15": require("@/assets/images/episodes/s33/ep15.webp"),

  // Season 34
  "s34/ep1": require("@/assets/images/episodes/s34/ep1.webp"),
  "s34/ep2": require("@/assets/images/episodes/s34/ep2.webp"),
  "s34/ep3": require("@/assets/images/episodes/s34/ep3.webp"),
  "s34/ep4": require("@/assets/images/episodes/s34/ep4.webp"),
  "s34/ep5": require("@/assets/images/episodes/s34/ep5.webp"),
  "s34/ep6": require("@/assets/images/episodes/s34/ep6.webp"),
  "s34/ep7": require("@/assets/images/episodes/s34/ep7.webp"),
  "s34/ep8": require("@/assets/images/episodes/s34/ep8.webp"),
  "s34/ep9": require("@/assets/images/episodes/s34/ep9.webp"),
  "s34/ep10": require("@/assets/images/episodes/s34/ep10.webp"),
  "s34/ep11": require("@/assets/images/episodes/s34/ep11.webp"),
  "s34/ep12": require("@/assets/images/episodes/s34/ep12.webp"),
  "s34/ep13": require("@/assets/images/episodes/s34/ep13.webp"),
  "s34/ep14": require("@/assets/images/episodes/s34/ep14.webp"),
  "s34/ep15": require("@/assets/images/episodes/s34/ep15.webp"),

  // Season 35
  "s35/ep1": require("@/assets/images/episodes/s35/ep1.webp"),
  "s35/ep2": require("@/assets/images/episodes/s35/ep2.webp"),
  "s35/ep3": require("@/assets/images/episodes/s35/ep3.webp"),
  "s35/ep4": require("@/assets/images/episodes/s35/ep4.webp"),
  "s35/ep5": require("@/assets/images/episodes/s35/ep5.webp"),
  "s35/ep6": require("@/assets/images/episodes/s35/ep6.webp"),
  "s35/ep7": require("@/assets/images/episodes/s35/ep7.webp"),
  "s35/ep8": require("@/assets/images/episodes/s35/ep8.webp"),
  "s35/ep9": require("@/assets/images/episodes/s35/ep9.webp"),
  "s35/ep10": require("@/assets/images/episodes/s35/ep10.webp"),
  "s35/ep11": require("@/assets/images/episodes/s35/ep11.webp"),
  "s35/ep12": require("@/assets/images/episodes/s35/ep12.webp"),
  "s35/ep13": require("@/assets/images/episodes/s35/ep13.webp"),
  "s35/ep14": require("@/assets/images/episodes/s35/ep14.webp"),
  "s35/ep15": require("@/assets/images/episodes/s35/ep15.webp"),

  // Season 36
  "s36/ep1": require("@/assets/images/episodes/s36/ep1.webp"),
  "s36/ep2": require("@/assets/images/episodes/s36/ep2.webp"),
  "s36/ep3": require("@/assets/images/episodes/s36/ep3.webp"),
  "s36/ep4": require("@/assets/images/episodes/s36/ep4.webp"),
  "s36/ep5": require("@/assets/images/episodes/s36/ep5.webp"),
  "s36/ep6": require("@/assets/images/episodes/s36/ep6.webp"),
  "s36/ep7": require("@/assets/images/episodes/s36/ep7.webp"),
  "s36/ep8": require("@/assets/images/episodes/s36/ep8.webp"),
  "s36/ep9": require("@/assets/images/episodes/s36/ep9.webp"),
  "s36/ep10": require("@/assets/images/episodes/s36/ep10.webp"),
  "s36/ep11": require("@/assets/images/episodes/s36/ep11.webp"),
};
